### ISSUE TITLE
Source Icons Not Working + Showing Movie Ratings For the US

### ISSUE THREAD

**Issue by iWockstar** [Mike-Aniki/Aniki-ReMake#1]
Whenever I'm in this view the sources don't show up in the top left corner of my screen, but they do in the gallery view (which I also included a photo of. You can see GameCube in the top left hand corner). Why is this? Is this fixable on my end?

Not sure if it helps but Steam is the only source that shows up in the top left corner in that specific view.

Also, I set up the theme how you recommended, and downloaded all of my ESRB ratings, but for some reason when I'm in this view it gives me movie ratings instead of gaming ratings. For example, it will say rated PG-13 instead of rated T; or it will say rated R, rather than rated M. This only happens in this view, not when I'm in game details

![Screenshot 2024-03-14 001800](https://github.com/Mike-Aniki/Aniki-ReMake/assets/138112895/56ea863f-214f-41c5-ba02-1481a93de47d)
![Screenshot 2024-03-14 001936](https://github.com/Mike-Aniki/Aniki-ReMake/assets/138112895/f62c9ccd-16ec-4cb8-a8c5-98c234c7f512)
![Screenshot 2024-03-14 001947](https://github.com/Mike-Aniki/Aniki-ReMake/assets/138112895/b2d07390-4bb6-43a2-a6f2-356b8305e1e0)

**Comment by Mike-Aniki** [comment]
The icons at the top of the home view are in the "Source" folder, and the icon displayed in the vertical view is the same as the one in the Filter bar. You have to put the same name on the source image as the source you put in playnite. 

The problem of classification comes from the fact that in the folder AgeRating the images of classification are those of Movie, I will change them in the next update, in the meantime if you want to change them just put the image of your choice in this folder and rename them with the same name as the image in this folder.

**Comment by iWockstar** [comment]
Dope, I'll get all that fixed on my end. Thanks for the clear and detailed response and I look forward to your future updates!

**Comment by iWockstar** [comment]
> The icons at the top of the home view are in the "Source" folder, and the icon displayed in the vertical view is the same as the one in the Filter bar. You have to put the same name on the source image as the source you put in playnite. 
> 
> 
> 
> The problem of classification comes from the fact that in the folder AgeRating the images of classification are those of Movie, I will change them in the next update, in the meantime if you want to change them just put the image of your choice in this folder and rename them with the same name as the image in this folder. 

Dope, I'll get all that fixed on my end. Thanks for the clear and detailed response and I look forward to your future updates!
